### ISSUE TITLE
Request to Add a License to the Code Repository

### ISSUE THREAD

**Issue by krauthorDFKI** [Jaewoong-Lee/sigir_2022_BISER#1]
First, thank you for sharing your work with the community!

I kindly ask if you could consider adding an open-source license to your repository for enabling others to reference your work.

Thank you for considering our request!

**Comment by Jaewoong-Lee** [comment]
Thank you for your attention to my code. I have added the license.txt file. Thank you!

**Comment by krauthorDFKI** [comment]
Great to hear, thank you for your prompt response and for adding the licence!
